In [1]:
pacman::p_load(dplyr,ggplot2,tidyverse,trend,rkt,lubridate,strucchange)

In [36]:
my_model <- efp(abund ~ DateTime, type = "OLS-CUSUM", data = frame_for_test)

In [2]:
infill_dates = read.csv("../output/metaT_informed_all_sol.csv")

In [47]:
rkt_result <- rkt(date = year(frame_for_test$DateTime), y = frame_for_test$abund, 
                  block = month(frame_for_test$DateTime),correct = FALSE)

Warning message:
“Unknown or uninitialised column: `DateTime`.”
Warning message:
“tz(): Don't know how to compute timezone for object of class NULL; returning "UTC".”
Warning message:
“Unknown or uninitialised column: `DateTime`.”
Warning message:
“tz(): Don't know how to compute timezone for object of class NULL; returning "UTC".”
Warning message in min(date):
“no non-missing arguments to min; returning Inf”

Error: first mandatory vector should be positive: year or year+fraction
       second mandatory vector should be numerical: measured data (ties allowed)
       third optional vector should be positive integer: season, month, site or a unique code for season and site
       fourth optional vector should be numerical: covariable
       all with the same length, at least 4

In [48]:
rkt_result

Analysis not performed

In [3]:
for_prob_test = infill_dates %>%
    dplyr::mutate(DateTimeForm=as.Date(paste0(format(as.Date(DateTime,format="%Y-%m-%d"), 
                                                     "%Y-%m"), "-01")))%>%
    dplyr::group_by(taxon,DateTimeForm) %>% 
    dplyr::summarize(abund=mean(abund,na.rm=TRUE))

all_stats = data.frame()
for (curr_group in unique(for_prob_test$taxon)) {
    frame_for_test = for_prob_test %>% dplyr::filter(taxon==curr_group) %>%
        dplyr::arrange(DateTimeForm)
    stats_test = mk.test(frame_for_test$abund)
    curr_fr = data.frame(statistic = stats_test$statistic,
               organism = curr_group,
               p_value = stats_test$p.value,
               total_abundance = sum(frame_for_test$abund),
               avg_abundance = mean(frame_for_test$abund))
    all_stats = all_stats %>% dplyr::bind_rows(curr_fr)
    print(curr_group)
    print(mk.test(frame_for_test$abund))
               
}

`summarise()` has regrouped the output.
ℹ Summaries were computed grouped by taxon and DateTimeForm.
ℹ Output is grouped by taxon.
ℹ Use `summarise(.groups = "drop_last")` to silence this message.
ℹ Use `summarise(.by = c(taxon, DateTimeForm))` for per-operation grouping
  (`?dplyr::dplyr_by`) instead.

[1] "Bacillariales"

	Mann-Kendall trend test

data:  frame_for_test$abund
z = -2.0188, n = 285, p-value = 0.04351
alternative hypothesis: true S is not equal to 0
sample estimates:
            S          varS           tau
-3.240000e+03  2.574105e+06 -8.181892e-02

[1] "Chaetocerotophycidae"

	Mann-Kendall trend test

data:  frame_for_test$abund
z = -0.98945, n = 285, p-value = 0.3224
alternative hypothesis: true S is not equal to 0
sample estimates:
            S          varS           tau
-1.592000e+03  2.585555e+06 -3.934750e-02

[1] "Coscinodiscales"

	Mann-Kendall trend test

data:  frame_for_test$abund
z = -12.38, n = 285, p-value < 2.2e-16
alternative hypothesis: true S is not equal to 0
sample estimates:
            S          varS           tau
-1.979900e+04  2.557616e+06 -5.076153e-01

[1] "Cryptomonadales"

	Mann-Kendall trend test

data:  frame_for_test$abund
z = 1.2892, n = 285, p-value = 0.1973
alternative hypothesis: true S is not equal to 0
sample estimates:
           S         varS          tau
2.074000e+03 2.585583e+06 5.124784e-02

[1] "Cymatosirales"

	Mann-Kendall trend test

data:  frame_for_test$abund
z = -0.12128, n = 285, p-value = 0.9035
alternative hypothesis: true S is not equal to 0
sample estimates:
            S          varS           tau
-1.960000e+02  2.585341e+06 -4.851793e-03

[1] "Florenciellales"

	Mann-Kendall trend test

data:  frame_for_test$abund
z = -1.8994, n = 285, p-value = 0.05751
alternative hypothesis: true S is not equal to 0
sample estimates:
            S          varS           tau
-3.053000e+03  2.581869e+06 -7.623006e-02

[1] "Gonyaulacales"

	Mann-Kendall trend test

data:  frame_for_test$abund
z = 0.61879, n = 285, p-value = 0.5361
alternative hypothesis: true S is not equal to 0
sample estimates:
           S         varS          tau
9.960000e+02 2.585581e+06 2.461143e-02

[1] "Gymnodiniales"

	Mann-Kendall trend test

data:  frame_for_test$abund
z = -2.3073, n = 285, p-value = 0.02104
alternative hypothesis: true S is not equal to 0
sample estimates:
            S          varS           tau
-3.711000e+03  2.585513e+06 -9.175539e-02

[1] "Hemiaulales"

	Mann-Kendall trend test

data:  frame_for_test$abund
z = 5.5243, n = 285, p-value = 3.307e-08
alternative hypothesis: true S is not equal to 0
sample estimates:
           S         varS          tau
8.884000e+03 2.585583e+06 2.195206e-01

[1] "Isochrysidales"

	Mann-Kendall trend test

data:  frame_for_test$abund
z = -1.5964, n = 285, p-value = 0.1104
alternative hypothesis: true S is not equal to 0
sample estimates:
            S          varS           tau
-2.568000e+03  2.585583e+06 -6.345441e-02

[1] "Leptocylindrales"

	Mann-Kendall trend test

data:  frame_for_test$abund
z = -3.8913, n = 285, p-value = 9.971e-05
alternative hypothesis: true S is not equal to 0
sample estimates:
            S          varS           tau
-6.258000e+03  2.585497e+06 -1.547325e-01

[1] "Lithodesmiales"

	Mann-Kendall trend test

data:  frame_for_test$abund
z = 1.2152, n = 285, p-value = 0.2243
alternative hypothesis: true S is not equal to 0
sample estimates:
           S         varS          tau
1.955000e+03 2.585529e+06 4.833068e-02

[1] "Mamiellales"

	Mann-Kendall trend test

data:  frame_for_test$abund
z = 6.8515, n = 285, p-value = 7.309e-12
alternative hypothesis: true S is not equal to 0
sample estimates:
           S         varS          tau
1.101800e+04 2.585583e+06 2.722511e-01

[1] "Melosirales"

	Mann-Kendall trend test

data:  frame_for_test$abund
z = -0.35697, n = 285, p-value = 0.7211
alternative hypothesis: true S is not equal to 0
sample estimates:
            S          varS           tau
-5.750000e+02  2.585578e+06 -1.420893e-02

[1] "Parmales"

	Mann-Kendall trend test

data:  frame_for_test$abund
z = -0.87813, n = 285, p-value = 0.3799
alternative hypothesis: true S is not equal to 0
sample estimates:
            S          varS           tau
-1.413000e+03  2.585556e+06 -3.492295e-02

[1] "Pelagomonadales"

	Mann-Kendall trend test

data:  frame_for_test$abund
z = -2.5109, n = 285, p-value = 0.01204
alternative hypothesis: true S is not equal to 0
sample estimates:
            S          varS           tau
-4.035000e+03  2.581218e+06 -1.008552e-01

[1] "Phaeocystales"

	Mann-Kendall trend test

data:  frame_for_test$abund
z = -3.4739, n = 285, p-value = 0.0005129
alternative hypothesis: true S is not equal to 0
sample estimates:
            S          varS           tau
  -5585.00000 2583720.66667      -0.13893

[1] "Prorocentrales"

	Mann-Kendall trend test

data:  frame_for_test$abund
z = 1.7171, n = 285, p-value = 0.08597
alternative hypothesis: true S is not equal to 0
sample estimates:
           S         varS          tau
2.762000e+03 2.585583e+06 6.824809e-02

[1] "Prymnesiales"

	Mann-Kendall trend test

data:  frame_for_test$abund
z = -0.74441, n = 285, p-value = 0.4566
alternative hypothesis: true S is not equal to 0
sample estimates:
            S          varS           tau
-1.198000e+03  2.585583e+06 -2.960217e-02

[1] "Pyramimonadales_X"

	Mann-Kendall trend test

data:  frame_for_test$abund
z = 1.3526, n = 285, p-value = 0.1762
alternative hypothesis: true S is not equal to 0
sample estimates:
           S         varS          tau
2.176000e+03 2.585583e+06 5.376822e-02

[1] "Rhizosoleniales"

	Mann-Kendall trend test

data:  frame_for_test$abund
z = -1.4492, n = 285, p-value = 0.1473
alternative hypothesis: true S is not equal to 0
sample estimates:
            S          varS           tau
-2.331000e+03  2.584975e+06 -5.775255e-02

[1] "Suessiales"

	Mann-Kendall trend test

data:  frame_for_test$abund
z = 1.0437, n = 285, p-value = 0.2966
alternative hypothesis: true S is not equal to 0
sample estimates:
           S         varS          tau
1.678000e+03 2.581942e+06 4.192904e-02

[1] "Thalassiosirales"

	Mann-Kendall trend test

data:  frame_for_test$abund
z = -0.15112, n = 285, p-value = 0.8799
alternative hypothesis: true S is not equal to 0
sample estimates:
            S          varS           tau
-2.440000e+02  2.585487e+06 -6.033632e-03

[1] "nitrogen"

	Mann-Kendall trend test

data:  frame_for_test$abund
z = -2.0218, n = 285, p-value = 0.0432
alternative hypothesis: true S is not equal to 0
sample estimates:
            S          varS           tau
-3.252000e+03  2.585583e+06 -8.035582e-02

[1] "phosphorus"

	Mann-Kendall trend test

data:  frame_for_test$abund
z = -4.8763, n = 285, p-value = 1.081e-06
alternative hypothesis: true S is not equal to 0
sample estimates:
            S          varS           tau
-7.842000e+03  2.585583e+06 -1.937732e-01

[1] "zoop"

	Mann-Kendall trend test

data:  frame_for_test$abund
z = -5.8589, n = 285, p-value = 4.659e-09
alternative hypothesis: true S is not equal to 0
sample estimates:
            S          varS           tau
-9.422000e+03  2.585583e+06 -2.328144e-01

In [4]:
all_stats

       statistic   organism             p_value      total_abundance
z...1   -2.0188209 Bacillariales        4.350584e-02 4.356475e-02
z...2   -0.9894487 Chaetocerotophycidae 3.224437e-01 1.401111e-01
z...3  -12.3795147 Coscinodiscales      3.373764e-35 3.109536e-02
z...4    1.2891992 Cryptomonadales      1.973288e-01 1.896927e+00
z...5   -0.1212762 Cymatosirales        9.034722e-01 1.223757e-01
z...6   -1.8994045 Florenciellales      5.751132e-02 5.296423e-01
z...7    0.6187910 Gonyaulacales        5.360541e-01 2.417099e-02
z...8   -2.3072813 Gymnodiniales        2.103914e-02 2.676917e-02
z...9    5.5243399 Hemiaulales          3.307266e-08 5.338583e-01
z...10  -1.5964179 Isochrysidales       1.103955e-01 5.615644e+00
z...11  -3.8912951 Leptocylindrales     9.971058e-05 5.543022e-02
z...12   1.2152059 Lithodesmiales       2.242876e-01 1.817186e-01
z...13   6.8514750 Mamiellales          7.309236e-12 5.132865e-01
z...14  -0.3569711 Melosirales          7.211134e-01 1.026822e-01
z...15  -0.8781277 Parmales             3.798744e-01 1.020794e+00
z...16  -2.5108659 Pelagomonadales      1.204354e-02 8.266194e-02
z...17  -3.4739425 Phaeocystales        5.128709e-04 5.166194e-01
z...18   1.7170666 Prorocentrales       8.596701e-02 2.843366e-02
z...19  -0.7444146 Prymnesiales         4.566257e-01 4.250488e-01
z...20   1.3526330 Pyramimonadales_X    1.761729e-01 3.121277e-01
z...21  -1.4491980 Rhizosoleniales      1.472823e-01 8.191739e-02
z...22   1.0436619 Suessiales           2.966418e-01 2.427287e-02
z...23  -0.1511246 Thalassiosirales     8.798775e-01 3.370260e-01
z...24  -2.0217977 nitrogen             4.319725e-02 1.059887e+03
z...25  -4.8763198 phosphorus           1.080833e-06 1.108551e+02
z...26  -5.8589222 zoop                 4.658808e-09 2.645688e+02
       avg_abundance
z...1  1.528588e-04
z...2  4.916180e-04
z...3  1.091065e-04
z...4  6.655884e-03
z...5  4.293886e-04
z...6  1.858394e-03
z...7  8.481049e-05
z...8  9.392690e-05
z...9  1.873187e-03
z...10 1.970401e-02
z...11 1.944920e-04
z...12 6.376092e-04
z...13 1.801005e-03
z...14 3.602885e-04
z...15 3.581734e-03
z...16 2.900419e-04
z...17 1.812700e-03
z...18 9.976724e-05
z...19 1.491399e-03
z...20 1.095185e-03
z...21 2.874294e-04
z...22 8.516795e-05
z...23 1.182548e-03
z...24 3.718901e+00
z...25 3.889651e-01
z...26 9.283115e-01

In [5]:
for_prob_test

     taxon         DateTimeForm abund
1    Bacillariales 2000-02-01    2.427143e-02
2    Bacillariales 2000-03-01    5.077156e-07
3    Bacillariales 2000-04-01    1.455483e-13
4    Bacillariales 2000-05-01    7.873015e-05
5    Bacillariales 2000-06-01    8.353231e-04
6    Bacillariales 2000-07-01    5.160132e-05
7    Bacillariales 2000-08-01    7.617844e-11
8    Bacillariales 2000-09-01    4.486833e-15
9    Bacillariales 2000-10-01    9.814342e-18
10   Bacillariales 2000-11-01    9.814342e-18
11   Bacillariales 2000-12-01    9.814342e-18
12   Bacillariales 2001-01-01    9.814342e-18
13   Bacillariales 2001-02-01    9.814342e-18
14   Bacillariales 2001-03-01    9.814342e-18
15   Bacillariales 2001-04-01    5.450275e-05
16   Bacillariales 2001-05-01    1.955099e-04
17   Bacillariales 2001-06-01    3.021675e-08
18   Bacillariales 2001-07-01   -1.124373e-17
19   Bacillariales 2001-08-01   -1.124373e-17
20   Bacillariales 2001-09-01   -1.124373e-17
21   Bacillariales 2001-10-01   -1.124373e-17
22   Bacillariales 2001-11-01   -1.124373e-17
23   Bacillariales 2001-12-01   -1.124373e-17
24   Bacillariales 2002-01-01   -1.124373e-17
25   Bacillariales 2002-02-01   -1.124373e-17
26   Bacillariales 2002-03-01   -1.124373e-17
27   Bacillariales 2002-04-01   -1.124373e-17
28   Bacillariales 2002-05-01   -1.124373e-17
29   Bacillariales 2002-06-01   -1.124373e-17
30   Bacillariales 2002-07-01   -1.124373e-17
⋮    ⋮             ⋮            ⋮
7381 zoop          2021-05-01   0.4706812
7382 zoop          2021-06-01   0.3950524
7383 zoop          2021-07-01   0.3417054
7384 zoop          2021-08-01   0.2820106
7385 zoop          2021-09-01   0.2534388
7386 zoop          2021-10-01   1.0808101
7387 zoop          2021-11-01   1.0776637
7388 zoop          2021-12-01   0.8760805
7389 zoop          2022-01-01   0.6912463
7390 zoop          2022-02-01   0.5454495
7391 zoop          2022-03-01   0.4801361
7392 zoop          2022-04-01   0.4522021
7393 zoop          2022-05-01   0.4155054
7394 zoop          2022-06-01   0.7109375
7395 zoop          2022-07-01   1.5625130
7396 zoop          2022-08-01   1.3406408
7397 zoop          2022-09-01   1.1703119
7398 zoop          2022-10-01   1.0937644
7399 zoop          2022-11-01   0.9013347
7400 zoop          2022-12-01   0.7732630
7401 zoop          2023-01-01   0.6850966
7402 zoop          2023-02-01   0.6248179
7403 zoop          2023-03-01   0.6131708
7404 zoop          2023-04-01   1.2387859
7405 zoop          2023-05-01   2.2213154
7406 zoop          2023-06-01   1.7000845
7407 zoop          2023-07-01   1.3586715
7408 zoop          2023-08-01   1.1880669
7409 zoop          2023-09-01   1.2452569
7410 zoop          2023-10-01   1.1104412